name: Deploy ngrok docs

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy ngrok docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy
        run: |
          aws s3 sync ./build s3://docs-s3.dev-ngrok.com --acl bucket-owner-full-control
          aws s3 sync ./build s3://docs-s3.stage-ngrok.com --acl bucket-owner-full-control 
          aws s3 sync ./build s3://docs-s3.ngrok.com --acl bucket-owner-full-control
  index-prod:
    name: Update Algolia Doc Search Index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: ${{ secrets.DEV_ALGOLIA_APPLICATION_ID }}
          algolia_api_key: ${{ secrets.DEV_ALGOLIA_API_KEY }}
          file: 'algolia_prod.config.json'